### ISSUE TITLE
series not generated

### ISSUE THREAD

**Issue by huiwang** [r12f/hexo-post-series#1]
Hello @r12f,

Thanks for the plugin. I have the same needs.

I find that the behavoir of this plugin is not deterministe. We use the filter 'before_post_render' prepares the posts series. But we can't ensure that all posts are scanned when this filter is called. When it's the case, the tag will return nothing.

Are you aware of this problem?

Regards

**Comment by r12f** [comment]
Hi @huiwang, the issue should be fixed now in v1.0.8.

It might be an issue in hexo. The local variable for posts is always empty even in 'after_post_render' filters during the clean generate. So I changed a different way to gather all the posts in the same series.
